version: "3.7"

services:
  app:
    image: keelezibel/whoami:1.0.0
    volumes:
      - .env:/app/.env
      - ./models:/models
      - ./data:/app/data
      - ./src:/app/src
    tty: true
    ports:
      - 7860:7860
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    shm_size: '8gb'
